# Generated by Django 3.0.3 on 2020-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
