# Generated by Django 3.0.3 on 2020-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200702_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
